title: Bookish
baseurl: ""

description: A barebones blogging theme for Jekyll.
lang: "en"

date_format_short: "%m/%d"
date_format_long: "%Y/%m/%d"

show_pinned_posts: true
group_by_year: false

google-analytics: false

markdown: kramdown

exclude:
    - Gemfile
    - Gemfile.lock
