# Blog Configuration
# ------------------
# All values must be populated unless specified otherwise




# Site Config

title: Bookish
    # Shown in header and footer

baseurl:
    # Can be blank
    # Set this if e.g. you have multiple sites with the same root url

date_format: "%b %d, %Y"
    # Default: "%b %d, %Y"

color_theme: light
    # [light]

contact:
    name:  Awjin Ahn
    email: awjinahn@gmail.com

    # The following can be blank if N/A:
    github_username:   Awjin
    linkedin_username: awjin
    medium_username:   awjypodgy
    twitter_username:  awjypodgy




# Homepage Config

listing_limit: 2
    # [blank = no limit]
    # Number of posts shown on the homepage
    # Remaining posts are kept in Archive
    # Feature posts do not count against the limit

show_dates: true
    # [true/false]
    # Show the published date next to the title

show_blurbs: true
    # [true/false]
    # Show the post blurb under the title
    # Blurb can be added in a post's front matter

show_featured: true
    # [true/false]
    # Pin featured posts to the top of the homepage

description: A crisp, readable Jekyll theme.
    # Can be blank
    # Included in head and footer

copyright: MIT License
    # Can be blank
    # Included in footer




# Post Config

recent_listing_limit: 3
    # Included at the end of the post
    # Displays links to the most recent posts




# Build Config

markdown: kramdown
    # Markdown engine
    # Default: kramdown

exclude:
    - Gemfile
    - Gemfile.lock
