title: Bookish
description: A barebones blogging theme for Jekyll.
baseurl: ""

date_format: "%Y/%m/%d"
lang: "en"

show_description: true
show_pinned_posts: true

google_analytics_tracking_code: ""
disqus_name: ""

markdown: kramdown
highlighter: rouge

exclude:
    - Gemfile
    - Gemfile.lock

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            comments: true
