#
# Site Config
#

title: Bookish
name:  Awjin Ahn
email: awjinahn@gmail.com

baseurl:
    # Can be blank
    # Set this if e.g. you have multiple sites with the same root url

date_format: "%Y/%m/%d"

color_theme: light
    # { light }

description: A crisp, readable Jekyll theme.
    # Can be blank
    # Included in head for SEO

lang: "en"
    # HTML lang
    # Default: "en"


#
# Homepage Config
#

listing_limit: 2
    # { blank = no limit }
    # Number of posts shown on the homepage
    # Remaining posts are listed in Archive
    # Pinned posts do not count against limit

show_dates: true
    # { true / false }
    # Show the published date next to the title

show_pinned: true
    # { true / false }
    # Show pinned posts at the top


#
# Build Config
#

markdown: kramdown
    # Markdown engine
    # Default: kramdown

exclude:
    - Gemfile
    - Gemfile.lock
